server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/product_db
    username: ${POSTGRES_USER:resell}
    password: ${POSTGRES_PASSWORD:resell}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cache:
    type: redis
    redis:
      time-to-live: 300000

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:}
  api-key:    ${CLOUDINARY_API_KEY:}
  api-secret: ${CLOUDINARY_API_SECRET:}

resilience4j:
  circuitbreaker:
    instances:
      cloudinary:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
